name: PR target

permissions:
  pull-requests: write
  contents: write

'on':
  pull_request_target:

jobs:
  update-container-tags:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ github.actor }}
      - uses: actions/checkout@v4
      - name: git fetch
        run: |
          git fetch
      - name: git checkout
        run: |
          git checkout ${{ github.head_ref }}
