name: PR target

'on':
  pull_request_target:

jobs:
  update-container-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: git fetch
        run: |
          git fetch
      - name: git checkout
        run: |
          git checkout ${{ github.head_ref }}
